// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

let cachedClient: SupabaseClient<Database> | null = null;
let clientInitializationError: Error | null = null;

export function getSupabaseClient(): SupabaseClient<Database> {
  if (cachedClient) {
    return cachedClient;
  }

  if (clientInitializationError) {
    throw clientInitializationError;
  }

  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseAnonKey) {
    clientInitializationError = new Error(
      'Supabase client is not configured. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set.',
    );
    throw clientInitializationError;
  }

  cachedClient = createClient<Database>(supabaseUrl, supabaseAnonKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return cachedClient;
}
